# Generated by Django 2.0.1 on 2018-04-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180421_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_full_name', models.CharField(max_length=100)),
                ('info_full_short_name', models.CharField(max_length=100)),
            ],
        ),
    ]
