# Generated by Django 2.0.1 on 2018-04-21 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180421_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_column_1', models.CharField(max_length=100)),
                ('row_column_2', models.CharField(max_length=100)),
                ('row_column_3', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='info_column_1_name',
            field=models.CharField(default='col1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='info_column_2_name',
            field=models.CharField(default='col2', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='info_num_colums',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rows',
            name='row_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Info'),
        ),
    ]
