# Generated by Django 2.0.1 on 2018-04-21 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180421_2019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rows',
            new_name='Row',
        ),
    ]
