# Generated by Django 2.0.1 on 2018-04-21 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180421_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Row_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_1', models.CharField(max_length=255)),
                ('row_2', models.CharField(max_length=255)),
                ('row_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Info')),
            ],
        ),
        migrations.RemoveField(
            model_name='col',
            name='col_row',
        ),
        migrations.RemoveField(
            model_name='row',
            name='row_info',
        ),
        migrations.DeleteModel(
            name='Col',
        ),
        migrations.DeleteModel(
            name='Row',
        ),
    ]
