# Generated by Django 2.0.1 on 2018-04-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180421_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='info_column_1_name',
            new_name='column_1_name',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='info_column_2_name',
            new_name='column_2_name',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='info_full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='info_num_colums',
            new_name='num_colums',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='info_full_short_name',
            new_name='short_name',
        ),
        migrations.RenameField(
            model_name='row_2',
            old_name='row_info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='tool_full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='tool_full_short_name',
            new_name='short_name',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='tool_url',
            new_name='url',
        ),
    ]
