# Generated by Django 2.0.1 on 2018-04-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180425_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='icon_name',
            field=models.CharField(default='priority high', max_length=100),
        ),
    ]
