# Generated by Django 2.0.4 on 2018-05-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180509_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='alphanumeric_order',
            field=models.BooleanField(default=False),
        ),
    ]
