# Generated by Django 2.0.4 on 2018-05-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_row_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='column_3_name',
            field=models.CharField(default='col3', max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='column_1_name',
            field=models.CharField(default='col1', max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='column_2_name',
            field=models.CharField(default='col2', max_length=100),
        ),
    ]
