# Generated by Django 2.0.4 on 2018-05-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20180524_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='korean_name',
            field=models.CharField(default='한국어', max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='full_name',
            field=models.CharField(default='Full Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='short_name',
            field=models.CharField(default='shortname', max_length=100),
        ),
    ]
