# Generated by Django 2.0.4 on 2018-06-07 17:03

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20180607_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='./images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='./images'),
        ),
    ]
