# Generated by Django 2.0.4 on 2018-06-08 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20180608_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_inserted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
