# Generated by Django 2.0.4 on 2018-06-09 13:47

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_profile_date_inserted'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='./images'),
        ),
        migrations.AddField(
            model_name='tool',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='./images'),
        ),
    ]
