# Generated by Django 2.0.4 on 2018-06-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20180609_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='blood_type',
            field=models.TextField(default='Blood Type'),
        ),
        migrations.AddField(
            model_name='member',
            name='instagram',
            field=models.TextField(default='Instagram'),
        ),
    ]
