# Generated by Django 2.0.4 on 2018-06-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20180611_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='blood_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='height',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='instagram',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(default='', max_length=100),
        ),
    ]
