# Generated by Django 2.0.4 on 2018-06-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20180611_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='row_2',
            name='is_link',
            field=models.BooleanField(default=False),
        ),
    ]
