# Generated by Django 2.0.4 on 2018-10-14 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestatus', '0002_auto_20181009_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_value', models.IntegerField(default='0')),
                ('humidity_value', models.IntegerField(default='0')),
                ('date_inserted', models.DateTimeField(default=datetime.datetime(2018, 10, 14, 15, 30, 29, 162864))),
            ],
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
