# Generated by Django 2.0.4 on 2018-10-14 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestatus', '0004_auto_20181014_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='date_inserted',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 15, 34, 24, 927530)),
        ),
    ]
