# Generated by Django 2.0.4 on 2018-12-28 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestatus', '0007_auto_20181014_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='date_inserted',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 28, 12, 37, 26, 780558)),
        ),
    ]
