# Generated by Django 2.0.4 on 2018-10-09 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestatus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='date_inserted',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 9, 11, 40, 8, 941160)),
        ),
    ]
