# Generated by Django 2.0.4 on 2018-10-14 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestatus', '0003_auto_20181014_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='date_inserted',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 15, 32, 25, 566047)),
        ),
    ]
