# Generated by Django 2.0.4 on 2018-10-14 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestatus', '0005_auto_20181014_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='date_inserted',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 15, 39, 43, 686710)),
        ),
    ]
