# Generated by Django 2.0.2 on 2018-02-22 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180216_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawl',
            name='startdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
