# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-23 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_crawl_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='Places_ID',
            field=models.TextField(default=1, max_length=50),
        ),
    ]
