# Generated by Django 2.0.1 on 2018-03-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180311_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pub',
            old_name='places_id',
            new_name='place_id',
        ),
    ]
