# Generated by Django 2.0.1 on 2018-04-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180312_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_full_name', models.CharField(max_length=100)),
                ('tool_full_short_name', models.CharField(max_length=100)),
                ('tool_icon_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='crawl',
            name='user',
        ),
        migrations.RemoveField(
            model_name='puboncrawl',
            name='crawl',
        ),
        migrations.RemoveField(
            model_name='puboncrawl',
            name='pub',
        ),
        migrations.DeleteModel(
            name='Crawl',
        ),
        migrations.DeleteModel(
            name='Pub',
        ),
        migrations.DeleteModel(
            name='PubOnCrawl',
        ),
    ]
