# Generated by Django 2.0.1 on 2018-04-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='tool_icon_url',
            new_name='tool_url',
        ),
    ]
