# Generated by Django 2.0.1 on 2018-04-21 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180421_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Col',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_data', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='row',
            name='row_column_1',
        ),
        migrations.RemoveField(
            model_name='row',
            name='row_column_2',
        ),
        migrations.RemoveField(
            model_name='row',
            name='row_column_3',
        ),
        migrations.AddField(
            model_name='col',
            name='col_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Row'),
        ),
    ]
