# Generated by Django 2.0.1 on 2018-04-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180421_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='row_2',
            old_name='row_1',
            new_name='col_1',
        ),
        migrations.RenameField(
            model_name='row_2',
            old_name='row_2',
            new_name='col_2',
        ),
    ]
