# Generated by Django 2.0.1 on 2018-04-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_info_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='icon_name',
            field=models.CharField(default='priority high', max_length=100),
        ),
    ]
