# Generated by Django 2.0.1 on 2018-04-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_tool_icon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='icon_name',
            field=models.CharField(default='priority_high', max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='icon_name',
            field=models.CharField(default='priority_high', max_length=100),
        ),
    ]
