# Generated by Django 2.0.1 on 2018-04-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180425_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='description',
            field=models.TextField(default='Info description.'),
        ),
    ]
