# Generated by Django 2.0.4 on 2018-05-24 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_info_numeric_first_col'),
    ]

    operations = [
        migrations.CreateModel(
            name='Row_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_1', models.CharField(max_length=255)),
                ('col_2', models.CharField(max_length=255)),
                ('col_3', models.CharField(max_length=255)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Info')),
            ],
        ),
    ]
