# Generated by Django 2.0.4 on 2018-05-24 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20180524_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='row_2',
            name='date_inserted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='row_3',
            name='date_inserted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='info',
            name='num_colums',
            field=models.IntegerField(default='2'),
        ),
    ]
