# Generated by Django 2.0.4 on 2018-06-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20180607_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birth_place',
            field=models.TextField(default='Birth Place'),
        ),
        migrations.AddField(
            model_name='member',
            name='height',
            field=models.TextField(default='Height'),
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.TextField(default='Position'),
        ),
    ]
