# Generated by Django 2.0.4 on 2018-06-08 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_profile_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agency',
            field=models.CharField(default='Agency', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='debut',
            field=models.CharField(default='Debut', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='debut_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='fandom',
            field=models.CharField(default='Fandom', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group_type',
            field=models.CharField(choices=[('BOYGROUP', 'Boy Group'), ('GIRLGROUP', 'Girl Group'), ('COEDGROUP', 'Co-ed Group'), ('SOLOIST', 'Soloist')], default='1', max_length=100),
        ),
    ]
