# Generated by Django 2.0.4 on 2018-06-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20180609_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='thumbnail',
            new_name='picture',
        ),
    ]
