# Generated by Django 2.0.4 on 2018-06-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20180622_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='thumbnail',
        ),
    ]
