# Generated by Django 2.0.4 on 2018-07-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20180628_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='description',
            field=models.TextField(default='Tool description.'),
        ),
    ]
