# Generated by Django 2.0.4 on 2018-07-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_tool_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word_Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Full Name', max_length=100)),
                ('short_name', models.CharField(default='shortname', max_length=100)),
                ('korean_name', models.CharField(default='한국어', max_length=100)),
            ],
        ),
    ]
