# Generated by Django 2.0.4 on 2018-12-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20180728_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='use_in_api',
            field=models.BooleanField(default=True),
        ),
    ]
